services:
# --- dispathcer ---
  dispathcer:
    build:
      context: .
      dockerfile: ./consumer-dockerfile
    networks:
    - logs
    depends_on:
      rbmq:
          condition: service_healthy
      db:
          condition: service_started
    command: ["./myapp"]
    env_file:
      - .env-consumer
    secrets:
      - rabbitmq_pass
      - sql_pass

# --- vendor ---
  vendor:
    build: 
      context: .
      dockerfile: ./producer-dockerfile
    networks:
    - logs
    depends_on:
      rbmq:
          condition: service_healthy
      db:
          condition: service_started
    ports:
      - 8080:8080
    command: ["./myapp"]
    env_file:
      - .env-consumer
    secrets:
      - rabbitmq_pass
      - sql_pass

# --- rabbitmq message broker ---
  rbmq:
    image: rabbitmq:4.2-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_CONFIG_FILE: /run/secrets/rabbitmq_conf
    secrets:
      - rabbitmq_conf
    networks:
        - logs
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 4

# --- postgres db---
  db:
    image: postgres:18.1-alpine
    ports:
      - 5432:5432
    networks:
      - logs
    env_file:
      - .env-db
    secrets:
      - postgres_pass
    healthcheck:
      test: ["CMD", "pg_isready", "-h", "localhost"]
    volumes:
      - ./models/sql/inventory_db.sql:/docker-entrypoint-initdb.d/init.sql

# --- secrets ---
secrets:
  rabbitmq_conf:
    file: ./rabbitmq.conf
  rabbitmq_pass:
    file: ./rabbitmq_pass
  sql_pass:
    file: ./sql_pass
  postgres_pass:
    file: ./postgres_pass

# --- networks ---
networks:
  logs:
    driver: bridge
