# https://kubernetes.io/docs/concepts/configuration/secret/
apiVersion: v1
kind: Secret
metadata:
  name: rbmq-secret
type: Opaque
stringData:
  RABBITMQ_DEFAULT_USER: app_user_1
  RABBITMQ_DEFAULT_PASS: app_pass_1
---

